


try:
    print(x)

except:
    print("Something, went wrong")


finally:
    print("try, Catch is finished.")        # Finally block code will must executed.....

